### ISSUE TITLE
Not be able to run with ollama locally

### ISSUE THREAD

**Issue by sytranvn** [platformatic/ai-warp-old#109]
I want to try with ollama models, but it didn't work out of the box. ~Debugging with `NODE_OPTIONS='--inspect' npm start` also hard, I can't locate the file in debugger for debugging.~ (As error message suggest use `platformatic start --inspect` instead). I'm trying to debug it.

![Screenshot 2024-08-14 at 09 19 18](https://github.com/user-attachments/assets/741886c4-6c8f-4904-9d95-4b334f99ce7d)

```
[08:57:55.278] INFO (nauseating-husband/98006): body/chatHistory/0 must have required property 'response'
    reqId: "e9679dda-464f-4b7a-8751-8be2f2f2bde7"
    res: {
      "statusCode": 400
    }
    err: {
      "type": "Error",
      "message": "body/chatHistory/0 must have required property 'response'",
      "stack":
          Error: body/chatHistory/0 must have required property 'response'
              at defaultSchemaErrorFormatter (/Users/sytd/Code/sytranvn/test-new-project/node_modules/fastify/lib/context.js:114:10)
              at wrapValidationError (/Users/sytd/Code/sytranvn/test-new-project/node_modules/fastify/lib/validation.js:228:17)
              at validate (/Users/sytd/Code/sytranvn/test-new-project/node_modules/fastify/lib/validation.js:146:16)
              at preValidationCallback (/Users/sytd/Code/sytranvn/test-new-project/node_modules/fastify/lib/handleRequest.js:92:25)
              at handler (/Users/sytd/Code/sytranvn/test-new-project/node_modules/fastify/lib/handleRequest.js:76:7)
              at /Users/sytd/Code/sytranvn/test-new-project/node_modules/fastify/lib/contentTypeParser.js:199:9
              at AsyncResource.runInAsyncScope (node:async_hooks:206:9)
              at done (/Users/sytd/Code/sytranvn/test-new-project/node_modules/fastify/lib/contentTypeParser.js:192:14)
              at Parser.defaultJsonParser [as fn] (/Users/sytd/Code/sytranvn/test-new-project/node_modules/fastify/lib/contentTypeParser.js:304:5)
              at IncomingMessage.onEnd (/Users/sytd/Code/sytranvn/test-new-project/node_modules/fastify/lib/contentTypeParser.js:283:27)
      "statusCode": 400,
      "code": "FST_ERR_VALIDATION",
      "validation": [
        {
          "instancePath": "/chatHistory/0",
          "schemaPath": "#/properties/chatHistory/items/required",
          "keyword": "required",
          "params": {
            "missingProperty": "response"
          },
          "message": "must have required property 'response'"
        }
      ],
      "validationContext": "body"
    }
```
I have tried calling ollama directly using their document and it works.
```
curl http://localhost:11434/api/chat -d '{
  "model": "codellama:13b",
  "messages": [
    {
      "role": "user",
      "content": "why is the sky blue?"
    }
  ]
}'
{"model":"codellama:13b","created_at":"2024-08-14T02:01:55.042533Z","message":{"role":"assistant","content":"\n"},"done":false}
{"model":"codellama:13b","created_at":"2024-08-14T02:01:55.183955Z","message":{"role":"assistant","content":"The"},"done":false}
{"model":"codellama:13b","created_at":"2024-08-14T02:01:55.32625Z","message":{"role":"assistant","content":" color"},"done":false}
...
```

Ollama npm library.
```
ollama = require('ollama').default
const response = await ollama.chat({
...   model: 'codellama:13b',
...   messages: [{ role: 'user', content: 'Why is the sky blue?' }],
... })
{
  model: 'codellama:13b',
  created_at: '2024-08-14T02:06:57.682171Z',
  message: {
    role: 'assistant',
    content: '\n' +
      'The sky appears blue because of a phenomenon called Rayleigh scattering, where shorter (blue) wavelengths of light are scattered more than longer (red) wavelengths by the tiny molecules of gases in the atmosphere. This results in a bluish hue to the sky during sunrise and sunset, as well as at dawn and dusk when the sun is low on the horizon. The blue color of the sky can also be affected by other factors such as atmospheric dust, pollution, and the presence of aerosols in the air.'
  },
  done_reason: 'stop',
  done: true,
  total_duration: 24378336417,
  load_duration: 21739084,
  prompt_eval_count: 26,
  prompt_eval_duration: 6657558000,
  eval_count: 124,
  eval_duration: 17675517000
}
```

**Comment by sytranvn** [comment]
After debugging a bit more, I found that `ai-providers/ollama.ts` is getting data from wrong source. 
https://github.com/ollama/ollama-js/blob/c03ea59c4292faa0a0ba6e498103dd69c7921566/src/utils.ts#L26-L28

Should await data from `response.itr.next()` instead. 
```ts
  import { Ollama, ChatResponse, Message, AbortableAsyncIterator } from 'ollama'

  // type OllamaStreamResponse = AsyncGenerator<ChatResponse>
  type OllamaStreamResponse = AbortableAsyncIterator<ChatResponse>

  async pull (controller: ReadableByteStreamController): Promise<void> {
    const { done, value } = await this.response.next()
    const { done, value } = await this.response.itr.next()
    if (done !== undefined && done) {
      controller.close()
      return
    }

    let response = value.message.content
    if (this.chunkCallback !== undefined) {
      response = await this.chunkCallback(response)
    }

    const eventData: AiStreamEvent = {
      event: 'content',
      data: {
        response
      }
    }
    controller.enqueue(encodeEvent(eventData))
  }
```
