### ISSUE TITLE
Cannot start new ai-warp project with create-platformatic 

### ISSUE THREAD

**Issue by sytranvn** [platformatic/ai-warp-old#115]
```
npx create-platformatic
 Hello "Sy Tran Dung", welcome to Platformatic 1.53.3!
? What kind of project do you want to create? Application
? Where would you like to create your project? testwapr
✔ Installing @platformatic/runtime...
? Which kind of project do you want to create? @platformatic/ai-warp
✔ Installing @platformatic/ai-warp...
? What is the name of the service? domineering-catastrophe
? What AI provider would you like to use? ollama
? What AI model would you like to use? llama3:latest
? Do you want to create another service? no
? Do you want to use TypeScript? no
? What port do you want to use? 3042
[17:05:29] INFO: /home/sytran/Code/sytran/testwapr/package.json written!
[17:05:29] INFO: /home/sytran/Code/sytran/testwapr/platformatic.json written!
[17:05:29] INFO: /home/sytran/Code/sytran/testwapr/.env written!
[17:05:29] INFO: /home/sytran/Code/sytran/testwapr/.env.sample written!
[17:05:29] INFO: /home/sytran/Code/sytran/testwapr/.gitignore written!
[17:05:29] INFO: /home/sytran/Code/sytran/testwapr/README.md written!
[17:05:29] INFO: /home/sytran/Code/sytran/testwapr/services/domineering-catastrophe/package.json written!
[17:05:29] INFO: /home/sytran/Code/sytran/testwapr/services/domineering-catastrophe/platformatic.json written!
[17:05:29] INFO: /home/sytran/Code/sytran/testwapr/services/domineering-catastrophe/.gitignore written!
[17:05:29] INFO: /home/sytran/Code/sytran/testwapr/services/domineering-catastrophe/global.d.ts written!
? Do you want to init the git repository? no
✔ Installing dependencies...
[17:05:41] INFO: Project created successfully, executing post-install actions...
[17:05:41] INFO: You are all set! Run `npm start` to start your project.
```

```
npm start

> start
> platformatic start

[17:06:13.419] ERROR (domineering-catastrophe/123309): The "path" argument must be of type string. Received undefined
    err: {
      "type": "TypeError",
      "message": "The \"path\" argument must be of type string. Received undefined",
      "stack":
          TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
              at new NodeError (node:internal/errors:405:5)
              at validateString (node:internal/validators:162:11)
              at join (node:path:1171:7)
              at stackable (file:///home/sytran/Code/sytran/testwapr/node_modules/@platformatic/ai-warp/dist/index.js:18:19)
              at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      "code": "ERR_INVALID_ARG_TYPE"
    }
FastifyError [Error]: The runtime exited before the operation completed
    at #sendCommand (/home/sytran/Code/sytran/testwapr/node_modules/@platformatic/runtime/lib/api-client.js:459:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RuntimeApiClient.start (/home/sytran/Code/sytran/testwapr/node_modules/@platformatic/runtime/lib/api-client.js:92:21)
    at async setupAndStartRuntime (/home/sytran/Code/sytran/testwapr/node_modules/@platformatic/runtime/lib/start.js:163:17)
    at async startCommand (/home/sytran/Code/sytran/testwapr/node_modules/@platformatic/runtime/lib/start.js:191:25)
    at async Command.func (file:///home/sytran/Code/sytran/testwapr/node_modules/platformatic/cli.js:48:57)
    at async Object.parseAsync (/home/sytran/Code/sytran/testwapr/node_modules/commist/index.js:82:7)
    at async file:///home/sytran/Code/sytran/testwapr/node_modules/platformatic/cli.js:79:18 {
  code: 'PLT_RUNTIME_RUNTIME_EXIT',
  statusCode: 500
}
```

I have to add `"showAiWarpHomepage": false` to platformatic.json to start. But I also need UI.

**Comment by mcollina** [comment]
This should be fixed now, give it a try!
